### ISSUE TITLE
Warning from ContextAwareCommaKeyMod.qml Unable to assign [undefined] to QString

### ISSUE THREAD

**Issue by martonmiklos** [tmikkonen/sailfish-arrowboard#1]
During the peek poke around the maliit-server I have seen the following in the output:
```
WARNING: file:///usr/share/maliit/plugins/com/jolla/arrowboard/ContextAwareCommaKeyMod.qml:16:21: Unable to assign [undefined] to QString
```
I will look around it deeper, just wanted to have an issue here as note.

**Comment by martonmiklos** [comment]
See PR #2

**Comment by tmikkonen** [comment]
Thank you for this! I reworked the conditional operation earlier after seeing your note about the warning but couldn't test & upload right away.

I realized a bit too late you'd made a PR (thanks!). Your function is more elegant than my solution but unfortunately while testing yours it didn't seem to work quite right: after typing any 1 character the comma key popper became empty so I ended up not using the PR. (Hopefully, I just didn't make some dumb mistake in a hurry.)

If you still see the warning, let me know and I'll re-test your PR for a more proper fix.

**Comment by martonmiklos** [comment]
I see the difference between your fix and mine: I return with '' (blanks string) when using noniOS keyboard, while you return with ','. Before this fix the code returned with undefined this is why I thought that returning with an empty string is a good idea. 

I have just tried out your version and no warnings present.
